# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Materialinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaterialInfo(object):
    def setupUi(self, MaterialInfo):
        MaterialInfo.setObjectName("MaterialInfo")
        MaterialInfo.resize(644, 70)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        font.setPointSize(12)
        MaterialInfo.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(MaterialInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CaseInfo_3 = QtWidgets.QFrame(MaterialInfo)
        self.CaseInfo_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CaseInfo_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CaseInfo_3.setObjectName("CaseInfo_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CaseInfo_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PositionLabel = QtWidgets.QLabel(self.CaseInfo_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PositionLabel.sizePolicy().hasHeightForWidth())
        self.PositionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.PositionLabel.setObjectName("PositionLabel")
        self.horizontalLayout_3.addWidget(self.PositionLabel)
        self.Postition = QtWidgets.QTextEdit(self.CaseInfo_3)
        self.Postition.setMinimumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Postition.setFont(font)
        self.Postition.setObjectName("Postition")
        self.horizontalLayout_3.addWidget(self.Postition)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.MaterialNameLabel = QtWidgets.QLabel(self.CaseInfo_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MaterialNameLabel.setFont(font)
        self.MaterialNameLabel.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.MaterialNameLabel.setObjectName("MaterialNameLabel")
        self.horizontalLayout_3.addWidget(self.MaterialNameLabel)
        self.MaterialName = QtWidgets.QTextEdit(self.CaseInfo_3)
        self.MaterialName.setMinimumSize(QtCore.QSize(150, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MaterialName.setFont(font)
        self.MaterialName.setObjectName("MaterialName")
        self.horizontalLayout_3.addWidget(self.MaterialName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.MaterialParaLabel = QtWidgets.QLabel(self.CaseInfo_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MaterialParaLabel.setFont(font)
        self.MaterialParaLabel.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.MaterialParaLabel.setObjectName("MaterialParaLabel")
        self.horizontalLayout_3.addWidget(self.MaterialParaLabel)
        self.MaterialPara = QtWidgets.QTextEdit(self.CaseInfo_3)
        self.MaterialPara.setMinimumSize(QtCore.QSize(150, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MaterialPara.setFont(font)
        self.MaterialPara.setObjectName("MaterialPara")
        self.horizontalLayout_3.addWidget(self.MaterialPara)
        self.verticalLayout.addWidget(self.CaseInfo_3)

        self.retranslateUi(MaterialInfo)
        QtCore.QMetaObject.connectSlotsByName(MaterialInfo)

    def retranslateUi(self, MaterialInfo):
        _translate = QtCore.QCoreApplication.translate
        MaterialInfo.setWindowTitle(_translate("MaterialInfo", "Form"))
        self.PositionLabel.setWhatsThis(_translate("MaterialInfo", "<html><head/><body><p>分析案例中产品的名称</p></body></html>"))
        self.PositionLabel.setText(_translate("MaterialInfo", "部件："))
        self.Postition.setPlaceholderText(_translate("MaterialInfo", "输入部件名称"))
        self.MaterialNameLabel.setWhatsThis(_translate("MaterialInfo", "<html><head/><body><p>所参考的设计标准，如《压力容器分析设计标准》、JB4732</p></body></html>"))
        self.MaterialNameLabel.setText(_translate("MaterialInfo", "材料："))
        self.MaterialName.setPlaceholderText(_translate("MaterialInfo", "输入材料名称或牌号"))
        self.MaterialParaLabel.setWhatsThis(_translate("MaterialInfo", "<html><head/><body><p>容器的用途，如“储罐”，“传热”</p></body></html>"))
        self.MaterialParaLabel.setText(_translate("MaterialInfo", "参数："))
        self.MaterialPara.setPlaceholderText(_translate("MaterialInfo", "输入相关参数名称"))
